# Tanya - Newsletter Generator (Ruby)
# Weekly digest generation

require 'json'
require 'date'

class NewsletterGenerator
  def initialize(articles)
    @articles = articles
  end
  
  def generate_weekly_digest
    digest = <<~HTML
      <!DOCTYPE html>
      <html>
      <head>
        <title>Weekly News Digest</title>
        <style>
          body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
          .header { background: linear-gradient(135deg, #2563eb, #8b5cf6); color: white; padding: 30px; border-radius: 12px; text-align: center; }
          .article { border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px; margin: 15px 0; }
          .sentiment { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: bold; }
          .positive { background: #d1fae5; color: #065f46; }
          .negative { background: #fee2e2; color: #991b1b; }
          .neutral { background: #f1f5f9; color: #475569; }
          .footer { text-align: center; margin-top: 30px; color: #64748b; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>📰 Weekly News Digest</h1>
          <p>#{Date.today.strftime('%B %d, %Y')}</p>
        </div>
    HTML

    sentiment_groups = @articles.group_by { |a| a['sentiment'] || 'neutral' }
    
    sentiment_groups.each do |sentiment, articles|
      digest += "<h2>#{sentiment.capitalize} News (#{articles.length})</h2>\n"
      articles.first(10).each do |article|
        digest += <<~HTML
          <div class="article">
            <h3><a href="#{article['link']}">#{article['title']}</a></h3>
            <p>#{article['content']&.slice(0, 200)}...</p>
            <span class="sentiment #{sentiment}">#{sentiment}</span>
            <span>#{article['reading_time'] || 5} min read</span>
          </div>
        HTML
      end
    end

    digest += <<~HTML
      <div class="footer">
        <p>Generated by Tanya News Aggregator</p>
        <p><a href="http://localhost:8502">View all articles →</a></p>
      </div>
      </body>
      </html>
    HTML

    digest
  end
  
  def send_via_email(digest_html)
    # In production, integrate with SendGrid, Mailgun, etc.
    puts "[Email] Sending weekly digest with #{@articles.length} articles"
    puts "[Email] Subject: Weekly News Digest - #{Date.today}"
    true
  end
end

# Ruby-based plugin system
module TanyaPlugin
  class Base
    def name; 'base'; end
    def process(articles); articles; end
  end
  
  class DeduplicatePlugin < Base
    def name; 'deduplicate'; end
    def process(articles)
      seen = Set.new
      articles.reject { |a| seen.include?(a['link']) || seen.add(a['link']) }
    end
  end
  
  class SentimentPlugin < Base
    POSITIVE = %w[good great excellent amazing success breakthrough]
    NEGATIVE = %w[bad terrible awful failure crisis disaster]
    
    def name; 'sentiment'; end
    def process(articles)
      articles.each do |a|
        text = "#{a['title']} #{a['content']}"
        words = text.downcase.split
        score = (words & POSITIVE).size - (words & NEGATIVE).size
        a['sentiment'] = score > 0 ? 'positive' : score < 0 ? 'negative' : 'neutral'
      end
    end
  end
end

if __FILE__ == $0
  sample = [
    { 'title' => 'AI Breakthrough', 'link' => 'https://x.com/1', 'content' => 'Great success in AI', 'sentiment' => 'positive' },
    { 'title' => 'Market Crash', 'link' => 'https://x.com/2', 'content' => 'Terrible news for investors', 'sentiment' => 'negative' }
  ]
  
  gen = NewsletterGenerator.new(sample)
  puts gen.generate_weekly_digest
end
